### ISSUE TITLE
Manually create a Task

### ISSUE THREAD

**Issue by ChrisKellaleaMaynard** [aehrc/snomio#103]
**As a:** Terminology Author,  
**I want to:**  manually create a Task for a Project
**So I can:**  add concepts or modify existing concepts within a Task branch.

---

The ticket management system may be used to create Tasks as well, however users should still be able to independently create Tasks within Snomio.

### Acceptance Criteria

1. [If I do A.]
1. [B should happen.]

[
Also, here are a few points that need to be addressed:

1. Constraint 1;
1. Constraint 2;
1. Constraint 3.
]

### Resources:

* Mockups: [Here goes a URL to or the name of the mockup(s) in inVision];
* Testing URL: [Here goes a URL to the testing branch or IP];
* Staging URL: [Here goes a URL to the feature on staging];

### Notes

[Some complementary notes if necessary:]

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

**Comment by kylynnloi** [comment]
duplicate #343
