### ISSUE TITLE
Complete the Login page and functionality

### ISSUE THREAD

**Issue by ChrisKellaleaMaynard** [aehrc/snomio#111]
**As a:** cybersecurity enforcer,  
**I want to:**  require users to login to Snomio using standard authentication approaches (e.g. username/password, SSO)
**So I can:**  ensure only authenticated users can modify the AMT data.

---
### Related Issues
* #34 
* #116 

### Acceptance Criteria

1. The login page is displayed if the user hasn't yet authenticated with Snomio, Managed Service, or the ticket management system.
2. The login page is displayed regardless of whether the user has navigated directly to the login page, to the list of Tasks, or directly into a Task.
3. The login page contains a brief description of Snomio:
> Welcome to Snomio, a medicine authoring tool which has been developed by CSIRO for the Australian SNOMED CT national release centre.
> 

4. The login page contains login instructions for the user, explaining the login process.
> This will redirect you to the SI Authoring Platform so you can login using your Authoring Platform credentials, then you will automatically be redirected back to Snomio.
> Do not attempt to login to Snomio or the SI Authoring Platform unless you have been granted access.
> 
> [ Login ]
> 
> Please ensure you logout of Snomio or the SI Authoring Platform at the end of your session.

5. The login page contains a "Contact Us" link to the support email address, so users can request access to the system:
> **Snomio Support:** snomio-support@csiro.au

6. The login page contains links to CSIRO, ADHA, and SNOMED International sites:
> **Associated Sites**
> NCTS: https://www.healthterminologies.gov.au
> Australian Digital Health Agency: https://www.digitalhealth.gov.au
> SNOMED International: https://www.snomed.org

7. The user can click a button to proceed to the login page from Managed Service Authoring Platform so they can login with their AP credentials.
8. After logging in using the AP screen, the user is forwarded to the dashboard page in Snomio.

### Wireframes
![image](https://github.com/aehrc/snomio/assets/140361342/22aa6941-ce8e-4c37-af80-1db90d4c259c)

### Testing
1. Verify the content in the Acceptance Criteria is displayed on the login page.
2. Login with invalid credentials - should not allow user to login to SNOMIO 
3. Use the different URL's and login - after login should redirect to https://dev-snomio.ihtsdotools.org/dashboard

- https://dev-snomio.ihtsdotools.org/dashboard/tasks
- https://dev-snomio.ihtsdotools.org/dashboard/tasks/edit/AUAMT-47
- https://dev-snomio.ihtsdotools.org/dashboard/tasks/all
- https://dev-snomio.ihtsdotools.org/dashboard/tasks/needReview
- https://dev-snomio.ihtsdotools.org/dashboard/tickets/board
- https://dev-snomio.ihtsdotools.org/dashboard/tickets/backlog
- https://dev-snomio.ihtsdotools.org/dashboard/products
- https://dev-snomio.ihtsdotools.org/dashboard/products/authoring

**Comment by kylynnloi** [comment]
looks good!

**Comment by ChrisKellaleaMaynard** [comment]
Happy with screen, ready for testing.

**Comment by HymaKanchiAU** [comment]
Verified the contents, invalid credentials, redirection and are behaving as expected in dev.
