### ISSUE TITLE
Search for a ticket in the AMT backlog

### ISSUE THREAD

**Issue by ChrisKellaleaMaynard** [aehrc/snomio#146]
**As a:** Terminology Author,  
**I want to:**  search for a ticket in the AMT backlog based on any of its fields
**So I can:**  locate tickets which are important for my current activity/research.

---
### Related issues
* #145 
* #123 
* #142 
* #227 

### Acceptance Criteria
1. A search field is available in the ticket backlog screen.
2. When a user enters a search term they have to press **Enter** or click a search button for the search to be performed.  There is no auto-search capability required (where the list of tickets is dynamically changed while the user is entering search criteria).
3. After entering a search term and activating the search, the list of tickets is reloaded based on the search term entered.
4. When the new list of tickets is loaded they are sorted according to the previous sort criteria before being displayed.
5. The filtering is applied by performing a partial-match search through all of the text fields within the tickets (including the title), plus its labels and other categorisations (including **Schedule**).
6. If a date (or partial date) is entered, the search function checks the text fields for the text version of the date (**dd/mm/yyyy** and **dd-mm-yyyy** formats) and performs a partial match on the release date (e.g. matching "August 2024" with "1/8/2024").

**Comment by kylynnloi** [comment]
related to #145  may not need this ticket

**Comment by kylynnloi** [comment]
search seems to work - but with a bug in rendering #268

**Comment by HymaKanchiAU** [comment]
@ChrisKellaleaMaynard , can you please revise the Acceptance criteria for this ticket.

**Comment by ChrisKellaleaMaynard** [comment]
Acceptance Criteria has been updated to reflect the extended capabilities which have been achieved for the advanced search function.

Note that while the ability to specify a field to search against is advantageous in certain situations, if the user does not specify a field for searching then the behaviour detailed in A/C 5 (searching across all fields) should occur.

**Comment by HymaKanchiAU** [comment]
Unable to search on schedule - https://github.com/aehrc/snomio/issues/356
