### ISSUE TITLE
Associate/Unassociate tickets to a task

### ISSUE THREAD

**Issue by ChrisKellaleaMaynard** [aehrc/snomio#15]
**As a:** Terminology Author,
**I want to:** associate tickets to Tasks
**So I can:** Allocate like products which need authoring to TAs.

---
[
User needs to be able to assign tickets to a task.
]

### Acceptance Criteria

1. User should be able to associate or unassociate non-deleted tickets in the backlog to an existing task
2. Multiple tickets can be associated to a task
3. A ticket can be associated to multiple tasks
4. A ticket does not need to be associated with a task 
5. Once a ticket is associated to one (or more) tasks, the tasks should be visible on the detailed view of the ticket and the table list of tickets

**Comment by clinnygee** [comment]
Api work done - Needs to be done on the ui now, this is blocked by #163 which is blocked by #155

**Comment by HymaKanchiAU** [comment]
1. Verify that able to associate multiple tickets to a task from the authoring screen- After associating multiple tickets the Ticket ID's should display in the = Pass

- My Tasks 
- All Tasks
- Tasks Requiring Review
- Tasks requested your Review
- Authoring Page summary section

2. Associate the same ticket to multiple task- This should display a message that only one active task can be associated to one ticket = Fail - https://github.com/aehrc/snomio/issues/311
3. Disassociate a ticket by clicking the delete button in the authoring screen - the ID should be removed from all the screens and the ticket should no longer be visible in the tickets section of the Authoring Screen = Fail -https://github.com/aehrc/snomio/issues/312

Unable to test as the functionality is not implemented.  https://github.com/aehrc/snomio/issues/313
4. Repeat the above scenarios from the Edit ticket screen.  
5. Repeat the above scenarios from the Ticket Backlog Screen
