### ISSUE TITLE
Automatically generate AMT flat-file and Refset TSVs for release

### ISSUE THREAD

**Issue by ChrisKellaleaMaynard** [aehrc/snomio#184]
**As a:** NCTS Release Manager,  
**I want to:**  have the additional AMT release files (flat-file and Refset TSVs) automatically generated as part of the release process
**So I can:**  include these files in the monthly AMT release.

---
This story has been added as the Datachecks tool is being decommissioned, with the validation being moved into the RVF tests.  A separate tool for performing only the release file extraction has not been specified as part of the development work for Snomio or the Managed Service process.

### Acceptance Criteria

1. When an AMT release is being generated, the ATM flat-file and reference set TSV files are automatically created and stored alongside the AMT RF2 release files.

**Comment by edeati** [comment]
We have the Flat file generator working within the AMTv4 pipeline that will have to be checked against the Release Bundle coming back from the Managed Service

We also have the TSV generator code that will have to be tested/modified for the Release Bundle

**Comment by ChrisKellaleaMaynard** [comment]
Closing as this is already covered in the Managed Service project tracking.
