### ISSUE TITLE
Updated link to send user to view classification and validation results in AP

### ISSUE THREAD

**Issue by ChrisKellaleaMaynard** [aehrc/snomio#229]
There is a task-level URL which can be used to take the user directly to the classification and validation results, instead of just taking them to the task editing screen:

https://uat-snowstorm.ihtsdotools.org/#/tasks/task/AUAMT/<task ID>/classify
https://uat-snowstorm.ihtsdotools.org/#/tasks/task/AUAMT/<task ID>/validate

For future reference, additional verbs are: _conflicts_ and _feedback_

**Comment by HymaKanchiAU** [comment]
@ChrisKellaleaMaynard Please confirm if the links need to be updated. As of 24/102023 when a classification is completed it takes us to the Authoring Page in SNOMIO and not the Classification Results Page. Similarly, once a Validation is completed also takes us to the Authoring Page in SNOMIO and not the Validation Results Page.

**Comment by ChrisKellaleaMaynard** [comment]
@HymaKanchiAU I've checked the current build and the classification results appear for AUAMT-44 and AUAMT-45, and validation results appear for AUAMT-39.  These were accessed by clicking on the _View Classification_ and _View Validation_ buttons.

If you click the pop-out icon on the pop-up message stating "Classification is completed", this will take you to the task, not the results.  It **should** take you to the classification results.

**Comment by HymaKanchiAU** [comment]
1. Click View Classification results on a Task in SNOMIO - https://uat-snowstorm.ihtsdotools.org/#/tasks/task/AUAMT/<task ID>/classify = Pass
2. Click View Validation results on a Task in SNOMIO - https://uat-snowstorm.ihtsdotools.org/#/tasks/task/AUAMT/<task ID>/validate =Pass
3. After reclassification Click View Classification results on a Task - https://uat-snowstorm.ihtsdotools.org/#/tasks/task/AUAMT/<task ID>/classify = Pass
4. Click on the pop up displayed after a classification is completed. -https://uat-snowstorm.ihtsdotools.org/#/tasks/task/AUAMT/<task ID>/classify = Fail - links to the task in SNOMIO
5. Click on the pop up displayed after validation is completed. -https://uat-snowstorm.ihtsdotools.org/#/tasks/task/AUAMT/<task ID>/validate = Fail - links to the task in SNOMIO
