### ISSUE TITLE
Update icons and Add tooltips for toolbar icons in main screen

### ISSUE THREAD

**Issue by ChrisKellaleaMaynard** [aehrc/snomio#264]
**As a:** Terminology Author,  
**I want to:**  be able to hover the mouse over any of the icons in the toolbar on the main screen and have a tooltip (pop-up description) appear with the title of the button and update the icons so they are more representative of what they are
**So I can:**  easily identify the icons in the toolbar without having to expand the entire toolbar panel.

---
### Acceptance Criteria
1. When the user is in the main editing screen and can see the toolbar down the left side of the screen, they can move the mouse over any of the icons in the toolbar and each one displays a pop-up label with that particular button's title in it.
2. As the user moves their mouse from one button to the next, the previous pop-up label disappears and a new one appears over the next button with its title displayed.
3. When the user moves the mouse away from all buttons, the pop-up label disappears.
4. The pop-up label does not interfere with the user's ability to click on the button.
5. The title displayed for each button matches the title displayed next to the button when the toolbar panel is expanded.
6. When the toolbar panel is expanded, hovering the mouse over the button still displays the pop-up label with its title.  This ensures a partially-obscured title in the panel is still completely rendered within the pop-up label.
7. If a button is hidden by screen logic, its title does not appear if the mouse is hovered over the space in which it was previously displayed.
8. New icons
My tasks - https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Apatient_list%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024
Tasks - https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Alist%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024
Tasks requiring review - https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Achecklist_rtl%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024
Board - https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Adashboard%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024
Backlog - https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Aconfirmation_number%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024
Product view - https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Aadmin_meds%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024
9. Update criteria for my task to include tasks owned to user and assigned for review, and remove "Tasks requested your review"

### Testing
1. Ensure that the icons are displayed as per Acceptance criteria
2. Ensure that labels are displayed on hovering the icons
3. ensure that labels when expanded the labels are still available on hover.

**Comment by clinnygee** [comment]
Hey. This is done, the product authoring menu option has been left there for now as I believe senjo is sitll using it, it is a super easy change to remove it when the time is right.

**Comment by kylynnloi** [comment]
looks good to me!

**Comment by ChrisKellaleaMaynard** [comment]
Updates to the toolbar look good.  Please hide the "Board" ticket view for now; a separate issue has been raised to create the view and restore its button in the toolbar.
#366

**Comment by clinnygee** [comment]
fixed in this pr https://github.com/aehrc/snomio/pull/372 can't be merged until uat-snowstorm branches are fixed

**Comment by clinnygee** [comment]
Done so passing to @HymaKanchiAU

**Comment by HymaKanchiAU** [comment]
Ensure that the icons are displayed as per Acceptance criteria= Pass
Ensure that labels are displayed on hovering the icons=Pass
ensure that labels when expanded the labels are still available on hover=Pass
