### ISSUE TITLE
when searching a ticket, results are not showing correctly in table (labels missing)

### ISSUE THREAD

**Issue by kylynnloi** [aehrc/snomio#268]
When searching on iteration.name, it's showing the correct results, but the iteration tag is not rendering

![Image](https://github.com/aehrc/snomio/assets/62123428/68637739-2660-4bc4-a1d6-eec802d2a647)

**Comment by clinnygee** [comment]
This has been fixed btw, not sure if you want to remove this ticket @kylynnloi

**Comment by kylynnloi** [comment]
completed with other fix
