### ISSUE TITLE
Task review functionality: bugs from earlier issue #37

### ISSUE THREAD

**Issue by ChrisKellaleaMaynard** [aehrc/snomio#273]
The following test cases failed per the testing for issue #37.
This issue has already been closed, hence the need for a separate bug-fixing ticket.

1. Reviewers are not displayed in My Tasks, Tasks requiring Review, Task requested your review
2. Able to Self assign as Reviewer
3. ~~Able to assign a user that has saved/edited the concept as a reviewer~~  [ _**2/11 CKM:** We are unable to query MS for historical modifications to concepts._ ]
4. ~~When feedback is "Mark as Unread" the Feedback status does not capture this information. This is not displayed in AP as well.~~ [ _**2/11 CKM:** The UI is detecting the status of the feedback correctly, so it appears there is a bug in AP which is preventing the "Unread" flag from being set correctly.  A bug report will be submitted to the Managed Service support team._ ]

These bugs need to be fixed so they can be re-tested.
Please review the content and Acceptance Criteria for the original issue when fixing these bugs.

### Testing
1. [ test case ]

**Comment by clinnygee** [comment]
Hello. For this 3. is unfixable, at least as far as I can see - this is not stored against the task. I am not sure if this would be available somewhere else in the managed service? 

4. Is also unfixable, it does not update the status of the task back to "unread". Perhaps a bug to raise with managed service. As soon as it is opened it is read - maybe this is why it is never updated correctly, as when you mark it as unread you are viewing it at the same time, so it might be related to that. Instead there probably should be a button that is mark as read.

**Comment by HymaKanchiAU** [comment]
@clinnygee , I was unable to see the task-41 in the Task requested your review.
Steps followed are

1. Logged in as hkanchi in SNOMIO 
2. Clicked My Tasks and Select Clinton Gillespie for AUAMT-41 from the reviewer list - received a message with the status code 500 as per screenshot
3. Logged in as cgillespie in SNOMIO in a different browser
4. clicked Task Requested your review

Expected:  The Task AUAMT-41 to be displayed in the Task requested your review.

Actual:  Task AUAMT-41 is not displayed in the Task requested your review.

![image](https://github.com/aehrc/snomio/assets/126848487/61327322-6510-45f2-9467-bad3c57ae739)
![image](https://github.com/aehrc/snomio/assets/126848487/bb1073dd-7319-49ad-9170-1f120222ef37)

**Comment by clinnygee** [comment]
@HymaKanchiAU Sorry i have only had a chance to look at this now. It appears that this issue was being caused because that task had a reviewer Thomas Tsang who I have no idea who that is, but I don't think he's part of csiro. 

So it wasn't showing the user in our list - because we only show users that are part of csiro atm or have a csiro email (this needs to be changed, we should be keeping our own list of users somewhere, something that there has been some push back against).

I'm still a little unsure why this was throwing an error though, but I fixed the task and will attempt to recreate with a different task on monday.

**Comment by ChrisKellaleaMaynard** [comment]
@clinnygee , **Thomas Tsang** is one of the terminologists in Sarah's team - a newbie, who may not have been granted access to the UAT environment yet.

I've made a note to raise the user whitelist with the wider Snomio dev team at some point, when we have everyone in the same meeting room again.

**Comment by HymaKanchiAU** [comment]
Retested for - User should not be able to Self assign as Reviewer = Pass. The Reviewer list does not show the Owner name for the tasks in My Tasks, All Tasks, Tasks Requiring Review

**Comment by ChrisKellaleaMaynard** [comment]
Items 3 and 4 have been removed due to Snomio's reliance on Managed Service functionality/behaviours.
Closing this ticket now.
