### ISSUE TITLE
Add "Externally-Requested Priority" field to AMT backlog tickets

### ISSUE THREAD

**Issue by ChrisKellaleaMaynard** [aehrc/snomio#274]
**As a:** Terminology Author,  
**I want to:**  record a priority for tickets which have been requested from external stakeholders within the AMT backlog
**So I can:**  ensure high-priority items are considered for authoring within appropriate timeframes.

---
### Related Issues
* #163 
* #262 

### Acceptance Criteria
1. When editing a ticket, the user has the ability to set an **Externally-Requested Priority** for the ticket.
2. The **Externally-Requested Priority** field uses a predefined list of values: "1a", "1b", "2", "3".
3. The user can set the **Externally-Requested Priority** to be blank/empty.
4. The **Externally-Requested Priority** is displayed as a column in the AMT backlog list, as a column towards the right side of the screen.

### Testing
1. Verify that user is able to set the priority from the Backlog screen.
2. Verify that user is able to set the priority from the edit screen.
3. Verify that priority field has the values "1a,1b,2,3" listed. 
4. In the Search option type priorityBucket.name:1a - should display only the entries that have been allocated that priority out of all the entries in the Backlog. repeat this with 1b,2,3, null.
5. Filter on the Priority using the 1a,1b,2,3, empty - should display only the entries that have been allocated that priority out of all the entries in the Backlog.
6. Verify that the Priority should be displayed in the ticket view on the task edit screen

**Comment by kylynnloi** [comment]
@clinnygee drop down for priority is blank - is this a me problem?

<img width="1318" alt="image" src="https://github.com/aehrc/snomio/assets/62123428/00ce4325-ad24-48e8-91ab-c1272e545812">
<img width="695" alt="image" src="https://github.com/aehrc/snomio/assets/62123428/ae7b040d-3660-4b96-92b0-1eb9f76120a6">

**Comment by clinnygee** [comment]
Oh sorry @kylynnloi I have to put the options in the db slipped my mind when pushing it to the dev env. Also, what order was it wanted in on the backlog page?

**Comment by clinnygee** [comment]
@kylynnloi They are there now

**Comment by ChrisKellaleaMaynard** [comment]
@clinnygee the priority doesn't render correctly on my laptop's screen - does it look okay on a proper monitor?
![image](https://github.com/aehrc/snomio/assets/140361342/a842afe7-f6ad-4b99-b034-dd86b224348a)

**Comment by clinnygee** [comment]
@ChrisKellaleaMaynard it's a bit better on my monitor yes but i'll fix it for a smaller screen that's pretty bad. Is the current order ok?

**Comment by ChrisKellaleaMaynard** [comment]
Yep, happy with the sort order - but there doesn't appear to be a way to clear the priority.
I've set a few tickets' priorities but I can't reset them to "no priority".

**Comment by kylynnloi** [comment]
it is also rendering overlapping for me and maybe i'm doing it wrong, but it also doesn't seem to be persisting when i go into the ticket details, edit it to add a priority, and then go back to the list.

**Comment by clinnygee** [comment]
Sorry I only just saw these comments now @ChrisKellaleaMaynard @kylynnloi. There is a fix for yours chris - i was expecting some status code that I wasn't actually sending oops. 

For yours kylynn I haven't been able to replicate it. Would you be able to create some steps? I pretty much tried click ticket in list -> edit priority -> browser back button -> it appears as updated in the list.

These were just merged to main so should be on dev- in ~5minutes

**Comment by kylynnloi** [comment]
@clinnygee do i need to click close after editing priority?

**Comment by ChrisKellaleaMaynard** [comment]
@kylynnloi I've tested and it seems to work correctly.

I had a second browser tab open; after clicking Edit and selecting a new priority, I could switch to the other tab and refresh and the new priority appears.

**Comment by kylynnloi** [comment]
have posted a screengrab on slack. i think its a refresh issue

**Comment by clinnygee** [comment]
@kylynnloi @ChrisKellaleaMaynard this is fixed now. It has also fixed another issue with iteration where the first iteration of one type e.g "october release" would appear in the first row that had it, then in no row after that.

**Comment by ChrisKellaleaMaynard** [comment]
@clinnygee - almost there, just need to improve A/C #3:
> The user can set the Externally-Requested Priority to be blank/empty.

Currently the user can clear the field by selecting the same option again (e.g. if "1b" is selected, then clicking in the field and selecting "1b" again will clear the field, as if they're clearing a tickbox) however that's very counter-intuitive for a single-select drop-down list.

Can you add a blank option at the top of the list ("", "1a", "1b", "2", "3") and when the user selects it the field is cleared?
...and since you were fixing the release field at the same time, maybe update that field with the same approach?
(this request can be moved to another story, but that seems a little like overkill)

**Comment by clinnygee** [comment]
@ChrisKellaleaMaynard Yes I can do this. I will do it for priority, state, iteration and assignee.

**Comment by clinnygee** [comment]
@ChrisKellaleaMaynard These are fixed now

**Comment by ChrisKellaleaMaynard** [comment]
Reviewed, ready for testing.

**Comment by HymaKanchiAU** [comment]
1. Verify that user is able to set the priority from the Backlog screen. = Pass
2. Verify that user is able to set the priority from the edit screen. = Pass
3. Verify that priority field has the values "1a,1b,2,3" listed. = Pass
4. In the Search option type priorityBucket.name:1a - should display only the entries that have been allocated that priority out of all the entries in the Backlog. repeat this with 1b,2,3 = Pass - Unable to search for null/empty values
5. Filter on the Priority using the 1a,1b,2,3, empty - should display only the entries that have been allocated that priority out of all the entries in the Backlog.= Fail - filtering only per page - existing issue with filters
6. Verify that the Priority should be displayed in the ticket view on the task edit screen = Pass
