### ISSUE TITLE
Unable to see whether the label is re-added

### ISSUE THREAD

**Issue by HymaKanchiAU** [aehrc/snomio#287]
Unable to see whether the label is re-added
1. Clicked on a ticket https://dev-snomio.ihtsdotools.org/dashboard/tickets/individual/2 which had the following labels to start with JiraExport
The_Peter_Doherty_Institute_for_Infection_and_Immunity
Fred_IT
Pfizer
Guidance

2. Clicked on Edit and unticked The_Peter_Doherty_Institute_for_Infection_and_Immunity
Fred_IT
Pfizer
3. Tried to click on the checkbox The_Peter_Doherty_Institute_for_Infection_and_Immunity

Actual: Unable to see "The_Peter_Doherty_Institute_for_Infection_and_Immunity" in the Labels section.

Expected: Should show all the selected labels 

Note:
Once I refresh the page, I can see that the label has been added. Also, noticed that due to this any new labels added after that are also not showing but after a refresh, they are available.

**Comment by clinnygee** [comment]
Just had a look at this and I can see the source of the bug, will fix it on Monday.

**Comment by HymaKanchiAU** [comment]
Retested this defect and working as expected, able to reassign labels.
![image](https://github.com/aehrc/snomio/assets/126848487/d332e555-bd3a-490f-b65d-f2d5d946ad0a)
