### ISSUE TITLE
Unable to view comments in the View Ticket from Task

### ISSUE THREAD

**Issue by HymaKanchiAU** [aehrc/snomio#298]
Navigate to a task and open a associated ticket 

Expected: Should be able to view the comments as there might be some updates from the reviewers.

Actual: Unable to see the comments section.

![image](https://github.com/aehrc/snomio/assets/126848487/0e56fc73-f5da-4eab-81be-47ac0429f6cc)

**Comment by ChrisKellaleaMaynard** [comment]
Not necessary to view comments within the ticket within the task screen.
Users can view the comments for the ticket by opening the ticket in its own tab.
Closing pending UAT feedback showing it needs to be implemented.
