### ISSUE TITLE
Search on the Backlog page not displaying results if the title has a comma

### ISSUE THREAD

**Issue by HymaKanchiAU** [aehrc/snomio#308]
Navigate to Backlog page in SNOMIO
in the Search option type [title =](title:Optix 0.4% / 0.3% eye drops, 15ml, status: closed)

Expected: Display the entry that matches the criteria.

Actual: Unable to display any results when there is a comma as anything after comma the system is looking for the column names and displays as undefined.
![image](https://github.com/aehrc/snomio/assets/126848487/fbd92e29-7fd8-402a-877f-ed480a8bd4f5)

**Comment by ChrisKellaleaMaynard** [comment]
Clinton has confirmed that following some other changes to the search mechanism, this issue no longer exists.
Closing this ticket as Fixed.
