### ISSUE TITLE
Unable to delete a ticket once it is associated to a task

### ISSUE THREAD

**Issue by HymaKanchiAU** [aehrc/snomio#312]
Open a task in the authoring view which has a ticket associated to it
Click on the tickets
Click on Delete button next to the ticket

Expected: the ticket should be disassociated from the task

Actual: no action is performed when clicked on delete option

![image](https://github.com/aehrc/snomio/assets/126848487/0bc46b2f-65eb-4d59-8607-35385a087a4c)

**Comment by HymaKanchiAU** [comment]
Retested and working as expected, hence closing the defect.
1.
![image](https://github.com/aehrc/snomio/assets/126848487/160a4649-715d-4973-853f-ecd58f5c5f31)
2.when delete is clicked 
![image](https://github.com/aehrc/snomio/assets/126848487/de53912c-035c-4e22-b76b-c230a327829c)
3. when delete is clicked on the confirmation modal
![image](https://github.com/aehrc/snomio/assets/126848487/8234577a-f301-4085-989f-773c6b8c50d6)

**Comment by HymaKanchiAU** [comment]
Reopening defect as the functionality is not working as part of the regression test. After clicking the delete button on the modal window the associated ticket is not deleted.
![image](https://github.com/aehrc/snomio/assets/126848487/a7380acb-a002-46ea-bde9-7c0877473323)

**Comment by clinnygee** [comment]
@HymaKanchiAU 
fixed

**Comment by HymaKanchiAU** [comment]
Retested and able to delete a ticket as expected.
Before delete
![image](https://github.com/aehrc/snomio/assets/126848487/72a58235-f112-405e-a937-ad151567dcdf)
after delete action
![image](https://github.com/aehrc/snomio/assets/126848487/b31d424a-7e2e-4c5d-80fe-03efeef9ad40)
