### ISSUE TITLE
Unable to associate a task from the ticket

### ISSUE THREAD

**Issue by HymaKanchiAU** [aehrc/snomio#313]
Task should be associated from the
Backlog screen
Edit Ticket screen

@ChrisKellaleaMaynard ,please add the Acceptance criteria, I have created this ticket as a placeholder.

**Comment by ChrisKellaleaMaynard** [comment]
Issue #32 was designed for this function, and has now been implemented.  This allows the user to associate a task to a ticket from the ticket details screen.

There is no need to set the task for a ticket from the backlog list, as we want the user to be presented with a more complicated dialog for selecting a task - which we can initiate from the ticket screen.

Closing this issue as a duplicate.
