### ISSUE TITLE
Unable to search for iteration, schedule, Labels, Status,Created in the backlog

### ISSUE THREAD

**Issue by HymaKanchiAU** [aehrc/snomio#356]
Navigate to the backlog screen
Enter Scedule:S8

Expected: Should display the entries where the Schedule =S8

Actual: All the entries are displayed, search criteria was not applied.
![image](https://github.com/aehrc/snomio/assets/126848487/3c72e123-1c64-40d4-a740-9acc7d54881b)

**Comment by clinnygee** [comment]
Hey @HymaKanchiAU this is done now. 

I think it was only schedule and created that didn't work (schedule worked with additionalFieldValue.valueOf=S8) it now works with schedule. 

So all of the below should now work

Priority:1a
Title:Some Title
Schedule:S8
Iteration:Some Name
Status:Some Status
Label: Some Label
Assignee: Some Assignee
Created: either dd/mm/yyyy or dd/mm/yy

**Comment by clinnygee** [comment]
You can also do something like

label:!jira and it will show you all of the one's that don't have jira export as a label. (currently all of them, so maybe will have to remove some to test)

you can also do created:12/10/2023, created:14/10/2023 to get all of the ones with created between those dates. I will change the name of this so its like createdAfter: and createdBefore:.

Also need to make it so you can choose multiple labels like label:alredhealth and label:nsw_health

Some of these aren't useful atm but all of these things will be needed for the filter part

**Comment by HymaKanchiAU** [comment]
Able to search as expected
![image](https://github.com/aehrc/snomio/assets/126848487/1b2c4808-5a4f-40a6-b4f4-53e9a7fa24d4)
![image](https://github.com/aehrc/snomio/assets/126848487/043d22eb-427b-48a3-b3a1-c1f796e1d811)
![image](https://github.com/aehrc/snomio/assets/126848487/688c7de0-39a4-4c09-93f4-e4985ff6dfd5)
