### ISSUE TITLE
7-box Search view displaying Synonym rather than Preferred term. 

### ISSUE THREAD

**Issue by HymaKanchiAU** [aehrc/snomio#357]
Navigate to product view.
Select SCTID and type 1324771000168103.
Select the CTPP that is loaded.

Expected: should display the PT for 354035004 - Liquid paraffin

Actual: Displaying the synonym for the MP 354035004 
![image](https://github.com/aehrc/snomio/assets/126848487/7fcc3d31-d2c6-43ed-88c5-5f4628524a64)
![image](https://github.com/aehrc/snomio/assets/126848487/fb9cf267-7424-41ef-aea0-4941b2339562)

**Comment by senjo-aehrc** [comment]
![image](https://github.com/aehrc/snomio/assets/135300932/2d41acaa-3e80-41d6-b366-56590204b040)
Can't reproduce in dev-snomio any more. Might be a UAT data loading issue during that time

**Comment by ChrisKellaleaMaynard** [comment]
Reopening and reassigning to Hyma for re-testing and closure.
