### ISSUE TITLE
Duplicate contained packages can be added

### ISSUE THREAD

**Issue by HymaKanchiAU** [aehrc/snomio#472]
Navigate to create product screen.
Click on search on the contained packages. 
In the search box type femme - select a term from the search results
Click on Add Package
Expected:
Indication that the package is being added. 
Actual: Not knowing what is happening, clicked multiple times on Add package and the same package was displayed based on the number of times Add package was clicked
![image](https://github.com/aehrc/snomio/assets/126848487/32d24747-4369-49e0-8454-e07b317c5614)

**Comment by ChrisKellaleaMaynard** [comment]
Closing as there are scenarios where having two copies of one package could be valid.  The review process should pick up on the duplication.
