### ISSUE TITLE
Validation for concentration strength/pack size/total quantity in atomic data entry form

### ISSUE THREAD

**Issue by ChrisKellaleaMaynard** [aehrc/snomio#507]
**As a:** Terminology Author,  
**I want to:**  enter the concentration strength, pack size, and total quantity for a product and have the UI assist me with ensuring the values reconcile
**So I can:**  submit a product to be created in AMT knowing there is no strength/pack size discrepancy.

---
Per issue #460 the first point raised by Dion will be fixed in that issue, whereas the other two will be fixed in this issue:
* UI to validate that the concentration strength, total quantity, and pack size all line up, and assist the user entering and editing these values by providing calculations
* back end to validate the concentration strength, total quantity, and pack size all line up

### Related Issues
* #460 

### Acceptance Criteria
1. When the user submits a new product for the atomic data entry form with a **Concentration Strength**, **Total Quantity**, and **Pack Size**, the UI confirms the values match the equation: **Total Quantity = Concentration Strength * Pack Size**  If they don't, an error message "The Total Quantity, Concentration Strength, and Pack Size values are not aligned." is displayed and the product is not submitted.
2. When the user is entering data into the atomic data entry form and enters one of these combinations of two ingredient fields leaving the third empty, the third field is automatically calculated when a _Reconcile Strength_ button is clicked:
* **Concentration Strength** and **Pack Size**  (calculates **Total Quantity** to three decimal places)
* **Concentration Strength** and **Total Quantity**  (calculates **Pack Size** as a whole number)
* **Pack Size** and **Total Quantity**  (calculates **Concentration Strength** to three decimal places)
3. If the user has entered data into the three fields **Concentration Strength**, **Total Quantity**, and **Pack Size**, then modifies one of the fields without emptying either of the other two, clicking the _Reconcile Strength_ button does not result in any field being updated.
4. If the user has entered data into only one of the fields **Concentration Strength**, **Total Quantity**, and **Pack Size**, then clicks the _Reconcile Strength_ button, none of the fields are updated.
5. If the user has not entered data into any of the fields **Concentration Strength**, **Total Quantity**, and **Pack Size**, then clicks the _Reconcile Strength_ button, none of the fields are updated.
6. When the user hovers the mouse over the _Reconcile Strength_ button, the fields **Concentration Strength**, **Total Quantity**, and **Pack Size** are highlighted with a blue border colour (matching the button's colour).
7. If a new product is submitted to the Snomio API with a **Concentration Strength**, **Total Quantity**, and **Pack Size** specified, the API confirms the values match the equation: **Total Quantity = Concentration Strength * Pack Size**  If they don't, an error message "The Total Quantity, Concentration Strength, and Pack Size values are not aligned." is returned and the submission is not processed.
8. All of the above functionality occurs for each product contained in the submission.  A separate _Reconcile Strength_ button is available for each product.

### Testing
1. [ test case ]

**Comment by senjo-aehrc** [comment]
@ChrisKellaleaMaynard , Validation rules are implemented and message is copied.
