### ISSUE TITLE
In the authoring page, view tickets associated with the task

### ISSUE THREAD

**Issue by kylynnloi** [aehrc/snomio#94]
**As a:** Terminology Author,  
**I want to:**  see all of the tickets associated with a Task and from within the main authoring page
**So I can:**  ensure the changes performed within the Task are in alignment with the related tickets.

---
### Related issues
* #15 
* #163 
* #145 

### Acceptance Criteria
1. When the user opens a Task, the authoring page displays a list of the associated tickets.
2. The tickets are displayed in a "summary" view, containing just the ticket ID, title, and category (e.g. PBS, TGA).

**Comment by ChrisKellaleaMaynard** [comment]
Initial UI to display tickets exists, however actual linking to ticket management system is required.

**Comment by HymaKanchiAU** [comment]
1. Verify that Ticket Id is displayed in the Authoring Page on the summary view. = Pass
2. Verify that when clicked on Tickets the Title of the ticket associated is displayed. =Pass
3. Ensure that when the ID displayed in the Authoring Page on the summary view is clicked the title is same as the title displayed in the Ticket tab in the Authoring Page = Pass
4. Ensure that a summary of the ticket can be viewable from the authoring page. =Pass
