### ISSUE TITLE
In the authoring page, clicking on a ticket shows read-only ticket information

### ISSUE THREAD

**Issue by kylynnloi** [aehrc/snomio#95]

**Comment by kylynnloi** [comment]
reviewed - all good

**Comment by HymaKanchiAU** [comment]
1. Verify that the following fields are displayed in read only format when viewing a ticket from the authoring page:

- Title = Pass
- Assignee = Failhttps://github.com/aehrc/snomio/issues/286
- ARTGID = Pass
- Effective Date = Pass
- TGA Schedule = Pass
- Inactive Date = Pass
- Date Requested = Pass
- AMT Flags = Pass
- Effective Date = Pass
- ARTGD Start Date = Pass
- Iteration = Pass
- State = Pass
- Priority = Pass
- Description = Pass
- Comments??? or suggestion that there are new comments added to the ticket? =Fail -https://github.com/aehrc/snomio/issues/298

2. Verify that when clicked on the title the ticket details are displayed =Pass
